### ISSUE TITLE
Raspbian Jessie

### ISSUE THREAD

**Issue by kikeonline** [rylnd/sd#10]
Tried the automatic install on a Raspberry Pi 2 Raspbian Jeesie. The colors are gone and:

-bash: //sd: No such file or directory

**Comment by kikeonline** [comment]
I deleted .bash_profile to restore.

**Comment by rylnd** [comment]
Hi @kikeonline! What's the main entry point for an interactive session on your machine? `sd` assumes it's .bash_profile, and that's currently not configurable (but I could see an argument for the default being .bashrc), so if yours is different you'll want to follow the [manual install](https://github.com/rylnd/sd#setup-manual) and just source wherever your sd definition lives.

I just recently set up a raspberry pi myself, and I believe I had to do something similar; I'll check later today and follow up.

**Comment by rylnd** [comment]
@kikeonline since the addition of a .bash_profile broke your environment on Raspbian, I'm guessing that you'd want to use .bashrc instead.

Would you mind trying the changes in #11 and verifying whether that works for you?

**Comment by kikeonline** [comment]
The instalation went smooth, i source it and everything but get -bash: sd: command not found

**Comment by rylnd** [comment]
@kikeonline can you please provide some more information so that I can help you troubleshoot?

* Is that error occurring after trying the new installation above?
* What is the full error that you see? Where is the error coming from?
* What configuration files do you have in your home directory (e.g. .bash_profile, .bashrc, .profile, etc)? What are the contents of those files?

**Comment by rylnd** [comment]
@kikeonline I'm going to close this issue for now. If you continue to have problems and can provide more information, I'd be happy to help.
